server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9420

logging:
  level: INFO
  loggers:
    "uk.co.kylethompson": DEBUG

applicationConfig:
  applicationVersionFilePath:
